"""prompt versions

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-13 03:07:00.937622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'AI_ASSIST', 'TEMPLATE', name='prompt_version_source'), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', 'version_number', name='uq_prompt_version_instance_number')
    )
    op.add_column('instances', sa.Column('current_prompt_version_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_instances_current_prompt_version_id', 'instances', 'prompt_versions', ['current_prompt_version_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_instances_current_prompt_version_id', 'instances', type_='foreignkey')
    op.drop_column('instances', 'current_prompt_version_id')
    op.drop_table('prompt_versions')
    # ### end Alembic commands ###
