"""theme settings

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-13 03:42:49.871381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('light_primary_color', sa.String(), nullable=False),
    sa.Column('light_secondary_color', sa.String(), nullable=False),
    sa.Column('dark_primary_color', sa.String(), nullable=False),
    sa.Column('dark_secondary_color', sa.String(), nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theme_settings')
    # ### end Alembic commands ###
